Onboarding challenge complete
UWOrbital/OBC-Firmware-Onboarding pull request #105
Opened 2023-11-12 04:12 UTC by ShourryaGuha

# Purpose
Onboarding

# New Changes
- Temp driver function implements, and os handler implemented

# Testing
- Unit and integration testing passed

2023-11-13 01:58 UTC, Navtajh04 requested changes
Looks good, just a couple of changes

2023-11-13 01:58 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  i2cReceiveFrom(devAddr, tempData, 2);  // receive 2 bytes since the temp register sends 2 bytes of data
log and return if these return an error code

2023-11-13 01:58 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  uint8_t tempData[2] = {0};
check if temp is NULL

2023-11-13 01:58 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +  return ERR_CODE_SUCCESS;
if we reach here then the xQueueSend was not successful due to the queue being full, so we should return an error code instead of success

2023-11-13 01:58 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +  if(xQueueSend(thermalMgrQueueHandle, (void*) event, 10) == pdPASS)
since this is being called in an ISR, block time should be 0

2023-11-13 01:58 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +          readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temp);
check return val

2023-11-13 01:58 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +          readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temp);
check return val

2023-11-16 03:58 UTC, ShourryaGuha commented
@Navtajh04 have addressed the PR comments

2023-11-16 18:00 UTC, Navtajh04 requested changes
just 2 minor changes other than that lgtm

2023-11-16 18:00 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +          RETURN_IF_ERROR_CODE(readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temp));
we generally should not return from a FreeRTOS task function so this should be LOG_IF_ERROR_CODE instead. Also RETURN_IF_ERROR_CODE would return the error code, but this is a void function

2023-11-16 18:00 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +          RETURN_IF_ERROR_CODE(readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temp));
same as above

2023-11-17 02:07 UTC, ShourryaGuha commented
> just 2 minor changes other than that lgtm

@Navtajh04 done

2023-11-17 22:22 UTC, Navtajh04 reviewed
LGTM

2023-11-17 22:22 UTC, closed without merging