Firmware Onboarding
UWOrbital/OBC-Firmware-Onboarding pull request #118
Opened 2024-01-03 04:38 UTC by HermanG05

# Purpose
Completed Firmware Onboarding

# New Changes
Made requested changes 

# Testing
Ran unit and integration tests to verify that all cases pass

# Outstanding Changes
- If there are non-critical changes (i.e. additional features) that can be made to this feature in the future, indicate them here.

2024-01-07 17:47 UTC, Gjjjiang requested changes
Overall implementation looks correct. There are just some error handling missing.

2024-01-07 17:47 UTC, Gjjjiang commented on lm75bd/lm75bd.c
> +  i2cSendTo(devAddr, &temp1, 1);
make sure to check if function returns a success or not. Feel free to use the RETURN_IF_ERROR_CODE macro in logging.h.

2024-01-07 17:47 UTC, Gjjjiang commented on lm75bd/lm75bd.c
> +  i2cReceiveFrom(devAddr, recTempBuff, 2);
make sure to check if function returns a success or not. Feel free to use the RETURN_IF_ERROR_CODE macro in logging.h.

2024-01-07 17:47 UTC, Gjjjiang commented on services/thermal_mgr/thermal_mgr.c
> +  if (thermalMgrQueueHandle == NULL || event == NULL)
thermalMgrQueueHandle == NULL would be an Invalid state error since it is not an argument to the function

2024-01-07 17:47 UTC, Gjjjiang commented on services/thermal_mgr/thermal_mgr.c
> +  thermal_mgr_event_t event;
try keeping scopes of variable as small as possible. In this case, event is only used inside the while loop, so its scope should be inside the while loop.

2024-01-07 17:47 UTC, Gjjjiang commented on services/thermal_mgr/thermal_mgr.c
> +          error_code_t errCode = readTempLM75BD(data.devAddr, &currtemp);
We usually want to also log the error code. We tend to use the LOG_IF_ERROR_CODE macro in logging.h

2024-01-07 17:47 UTC, Gjjjiang commented on services/thermal_mgr/thermal_mgr.c
> +          error_code_t errCode = readTempLM75BD(data.devAddr, &currtemp);
We usually want to also log the error code. We tend to use the LOG_IF_ERROR_CODE macro in logging.h

2024-01-11 00:27 UTC, dgobalak requested changes
Just a few more changes. You can ignore the nits if u want

2024-01-11 00:27 UTC, dgobalak commented on lm75bd/lm75bd.c
> +#define TEMP_ADDR 0x00
Use the same naming convention as the configuration reg. So `LM75BD_REG_TEMP`

2024-01-11 00:27 UTC, dgobalak commented on lm75bd/lm75bd.c
> +  uint8_t temp1 = TEMP_ADDR;
This isn't very descriptive. This variable holds the address of the temperature register. So something like `tempRegAddr` would be better.

2024-01-11 00:27 UTC, dgobalak commented on lm75bd/lm75bd.c
> +  }
Replace with `RETURN_IF_ERROR_CODE(i2cSendTo(devAddr, &temp1, 1));`. This will log and return the error code if `i2cSendTo` fails.

2024-01-11 00:27 UTC, dgobalak commented on lm75bd/lm75bd.c
> +  uint8_t recTempBuff[2];
nit: good practice to initialize buffers to 0. So `uint8_t recTempBuff[2] = {0}`.

2024-01-11 00:27 UTC, dgobalak commented on lm75bd/lm75bd.c
> +  }
Replace with `RETURN_IF_ERROR_CODE(i2cReceiveFrom(devAddr, recTempBuff, 2));. This will log and return the error code if i2cReceiveFrom fails.

2024-01-11 00:27 UTC, dgobalak commented on lm75bd/lm75bd.c
> +  }
This logic can be simplified to the following:
```
int16_t regVal = recTempBuff[0] << 8 | recTempBuff[1];
*temp = (float)(regVal >> 5) * 0.125f;
```

2024-01-11 00:27 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +  if (xQueueSend(thermalMgrQueueHandle, (void *) event, 0) == pdTRUE)
nit: I would check if `thermalMgrQueueHandle == NULL` (this could occur if the queue hasn't been created yet) before sending to the queue.

2024-01-11 00:27 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +  thermal_mgr_event_t interrupt;
Good practice to initialize structs to 0s. So `thermal_mgr_event_t interrupt = {0};`. We've had bugs in the past due to structs containing garbage data.

2024-01-11 00:27 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +  lm75bd_config_t data = *(lm75bd_config_t *) pvParameters;
In general, the greater the variable scope, the more descriptive the variable name should be. So make this `lm75bdConfig` or something.

2024-01-11 00:27 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +        if (event.type == OVER_TEMPERATURE_SHUTDOWN)
The event can't be both OVER_TEMPERATURE_SHUTDOWN and THERMAL_MGR_EVENT_MEASURE_TEMP_CMD, so this should be an `else if`

2024-01-11 00:27 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.h
> +  OVER_TEMPERATURE_SHUTDOWN,
Use the same naming convention as the other enum. So `THERMAL_MGR_EVENT_<...>`.

2024-01-11 00:27 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +          LOG_IF_ERROR_CODE(errCode);
We don't need to log if the function succeeded. Only log failures

2024-01-11 00:27 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +          LOG_IF_ERROR_CODE(errCode);
We don't need to log if the function succeeded. Only log failures

2024-01-12 02:20 UTC, Navtajh04 requested changes

2024-01-12 02:20 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +        float currtemp;
nit: variable names should be camelCase

2024-01-12 02:20 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +          else if (errCode != ERR_CODE_SUCCESS)
nit: this can just be an else instead of else if since if its not == ERR_CODE_SUCCESS then its != ERR_CODE_SUCCESS

2024-01-12 02:20 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +          else if (errCode != ERR_CODE_SUCCESS)
same as above

2024-01-15 06:05 UTC, dgobalak commented
lgtm. Send me your email on Discord and I'll add you to the Notion and GitHub.

2024-01-16 01:09 UTC, closed without merging