Orbital FW Onboarding
UWOrbital/OBC-Firmware-Onboarding pull request #120
Opened 2024-01-04 22:26 UTC by Starbey

# Purpose
Explain the purpose of the PR here, including references to any existing Notion tasks.

# New Changes
- Explain new changes

# Testing
- Explain tests that you ran to verify code functionality.

# Outstanding Changes
- If there are non-critical changes (i.e. additional features) that can be made to this feature in the future, indicate them here.

2024-01-05 03:16 UTC, Navtajh04 requested changes
Looks good overall, just a couple of changes

2024-01-05 03:16 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  RETURN_IF_ERROR_CODE(i2cReceiveFrom(devAddr,buf,2));//receives temp. data from internal temp. register; stores in buf
it would be more readable to use a separate buf for sending n receiving

2024-01-05 03:16 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  int16_t tempData=buf[1]|(buf[0]<<8);//int16_t => signed value
nit: add spaces around operators (=, ==, <<, |, etc) to make it easier to ready

2024-01-05 03:16 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  int16_t tempData=buf[1]|(buf[0]<<8);//int16_t => signed value
this applies everywhere else as well

2024-01-05 03:16 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +  error_code_t errCode;
unused variable (compiler would give a warning about this so its good to check and resolve all compiler warnings)

2024-01-05 03:16 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +  if (xQueueSend(thermalMgrQueueHandle,event,portMAX_DELAY)==errQUEUE_FULL) return ERR_CODE_QUEUE_FULL;//task will remain blocked as long as queue is full
check to make sure the queue has already been created (ie thermalMgrQueueHandle is not NULL)

2024-01-05 03:16 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +  if (xQueueSend(thermalMgrQueueHandle,event,portMAX_DELAY)==errQUEUE_FULL) return ERR_CODE_QUEUE_FULL;//task will remain blocked as long as queue is full
siince you are using this function in an ISR you should never be blocking

2024-01-05 03:16 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +  float temp;
in general try to limit the scope of your variables to the smallest scope possible

2024-01-15 06:21 UTC, dgobalak reviewed
lgtm. Send me your email on Discord and I'll add you to the Notion and GitHub.

I made a few more comments, so take a look at those. No need to fix them. Just keep them in mind when working on future tasks.

2024-01-15 06:21 UTC, dgobalak commented on lm75bd/lm75bd.h
> +#define LM75BD_OBC_I2C_ADDR 0b1001111
Usually hex is preferred since it's easier to read
```suggestion
#define LM75BD_OBC_I2C_ADDR 0x4F
```

2024-01-15 06:21 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +#include <logging.h>
We're not super consistent about this, but we tend to keep the angle bracket includes for standard libs and the hal/freertos files.
```suggestion
#include "logging.h"
```

2024-01-15 06:21 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +  if (thermalMgrQueueHandle == NULL) return ERR_CODE_INVALID_ARG;
ERR_CODE_INVALID_STATE would be more appropriate.
```suggestion
  if (thermalMgrQueueHandle == NULL) return ERR_CODE_INVALID_STATE;
```

2024-01-15 06:21 UTC, dgobalak commented on services/thermal_mgr/thermal_mgr.c
> +  event.type=THERMAL_MGR_EVENT_INTERRUPT;
This ensures the rest of the struct gets initialized to zero (if the struct held more than just `type`).
```suggestion
  thermal_mgr_event_t event = {.type = THERMAL_MGR_EVENT_INTERRUPT};
```

2024-01-16 21:48 UTC, closed without merging