Rohan Mandhotra: UWOrbital Onboarding
UWOrbital/OBC-Firmware-Onboarding pull request #125
Opened 2024-01-27 03:20 UTC by RohanMandhotra

# Purpose
Finished implementing the LM75BD sensor functions, thermal management task and OS Handler

# New Changes
- Changed lm75bd.c, lm75bd.h, thermal_mgr.c, thermal_mgr.h

# Testing
- Ran integration and build tests and passed them without any errors

2024-01-31 07:41 UTC, Navtajh04 requested changes
Looks good, just a couple of changes

2024-01-31 07:41 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> -
check if temp is NULL

2024-01-31 07:41 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +      {
nit: 
```suggestion
      if (tempEvent.type == THERMAL_MGR_EVENT_MEASURE_TEMP_CMD) {
```

2024-01-31 07:41 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +        errCode = readTempLM75BD(LM75BD_OBC_I2C_ADDR, &tempVal);
this should be logged if it does not return success

2025-09-07 03:51 UTC, Adityya-K commented
Closed due to a lot of time passing.

2025-09-07 03:51 UTC, closed without merging