Finished onboarding challenge
UWOrbital/OBC-Firmware-Onboarding pull request #140
Opened 2024-05-11 16:02 UTC by gracexuwt

# Purpose
The purpose of this PR is to finish the Orbital Firmware onboarding: https://uworbital.notion.site/Firmware-Onboarding-Challenge-24340dfccb0547a5a7246ce6d7207c28#2d1d1b1b368c484fa725838805c14911

# New Changes
- Added functionality to driver functions, task, and OS handler

# Testing
- Ran the unit tests and integration test and passed.

# Outstanding Changes
- N/A

2024-05-11 17:29 UTC, Gjjjiang requested changes
just some changes, but overall, good work.

2024-05-11 17:29 UTC, Gjjjiang commented on services/thermal_mgr/thermal_mgr.c
> +    float temp;
usually, we want to minimize the scope of the variables. temp is only used inside the line 72's if statement scope.

2024-05-11 17:29 UTC, Gjjjiang commented on services/thermal_mgr/thermal_mgr.c
> +        }
Should make sure the temperature reading was successful before performing an action.

2024-05-11 17:29 UTC, Gjjjiang commented on lm75bd/lm75bd.c
> +  float tempConst = 0.125f;
This can be a define constant.

2024-05-11 21:02 UTC, Yarik-Popov requested changes
Overall good, not much to change

2024-05-11 21:02 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  }
This logic is unnecessarily complex. Just bit shift 5he result then multiply by the temp const

2024-05-11 21:02 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  if(xQueueSend(thermalMgrQueueHandle, event, 0) == errQUEUE_FULL) {
Check that the queue isn't null, if so then return invalid state

2024-05-11 21:02 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +      errCode = readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temp);
In general, it is best to perform logic required by an event after checking the type. Lets say we add an event that doesn't require read the temperature, then reading the temperature when receiving this new event might cause issues.

2024-05-11 21:02 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +        } else if(event.type == THERMAL_MGR_EVENT_INTERRUPT) {
Additionally log an error if some other event is received

2024-05-12 14:50 UTC, Yarik-Popov commented
Lgtm, dm me your email and I'll add you to the notion

2024-05-12 14:50 UTC, closed without merging