Firmware Onboarding Challenge
UWOrbital/OBC-Firmware-Onboarding pull request #149
Opened 2024-08-26 20:07 UTC by KayaanT

# Purpose
Explain the purpose of the PR here, including references to any existing Notion tasks.

# New Changes
- Explain new changes

# Testing
- Explain tests that you ran to verify code functionality.

# Outstanding Changes
- If there are non-critical changes (i.e. additional features) that can be made to this feature in the future, indicate them here.

2024-08-26 21:11 UTC, kepler452b123 reviewed
Great overall. Only spotted some minor things to change

2024-08-26 21:11 UTC, kepler452b123 commented on lm75bd/lm75bd.c
> +  buffer[0] = 0x00U;
I would create 2 buffers, one for writing, and one for the results

2024-08-26 21:11 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +          LOG_ERROR_CODE(errCode);
Use the LOG_IF_ERROR_CODE macro here. More details can be found in the onboarding document in notion, or in /sys/logging.h

2024-08-26 21:11 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +    if (xQueueReceive(thermalMgrQueueHandle, &event, portMAX_DELAY) == pdPASS) {
Set the blocking time to be lower than portMAX_DELAY. The reason is we want thermalMgr to obtain from the queue if there is an event, not wait a long time for an event to pop up

2024-08-26 21:11 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +    if (xQueueReceive(thermalMgrQueueHandle, &event, portMAX_DELAY) == pdPASS) {
It's cleaner to just check if xQueueReceive is pdFALSE instead of pdPASS and then do a continue to skip the iteration of the loop if it is false.

2024-08-26 22:07 UTC, Yarik-Popov requested changes
Minor changes, otherwise quite good

2024-08-26 22:07 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +        LOG_IF_ERROR_CODE(readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temp));
In general it is best to only read from the temperature sensor when a event to do so is received so move this into the read temp and over temperature

2024-08-26 22:07 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +    uint8_t readBuffer[2];
Good practice is to initialize buffers and variables, the errCode above is the exception

2024-08-26 22:07 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.h
> +  THERMAL_MGR_EVENT_OS_INT
I would make this a bit more descriptive

2024-08-28 00:08 UTC, Yarik-Popov commented
Lgtm, dm me your email and I'll add you to the notion.

2024-08-28 00:08 UTC, closed without merging