Completed onboarding challenge
UWOrbital/OBC-Firmware-Onboarding pull request #157
Opened 2024-09-15 19:51 UTC by justinbax

# Purpose
Finished implementing the temperature sensor driver and the thermal management task

# New Changes
- Driver function to retrieve temperature (`readTempLM75BD`)
- Thermal management task to call driver function on event
- Over-temperature interrupt handler

# Testing
All unit tests are passing, integration tests give expected behaviour

# Outstanding Changes
None

2024-09-15 20:25 UTC, kepler452b123 requested changes
Few comments to improve clarity

2024-09-15 20:25 UTC, kepler452b123 commented on lm75bd/lm75bd.h
> +#define LM75BD_OBC_I2C_ADDR 0b1001111
our standard is to use hex instead of binary for readability

2024-09-15 20:25 UTC, kepler452b123 commented on lm75bd/lm75bd.c
> +  uint8_t ptrByte = 0x00;
I think it's more clear to just make 2 buffers using uint8_t writeByte[1] = {0} (or just one buffer with length 2)

2024-09-15 20:25 UTC, kepler452b123 commented on lm75bd/lm75bd.c
> +    tempValue++;
We don't really ever expect it to be negative so you don't have to take 2s complement here

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +  }
you could make it shorter than 10 ticks so it blocks for less time

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +  LOG_IF_ERROR_CODE(thermalMgrSendEvent(&event));
Good instinct to use LOG_IF_ERROR_CODE, but this is an exception where we don't want to log inside of an ISR.

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +          lm75bd_config_t config = *(lm75bd_config_t *)(pvParameters);
This variable isn't really necessary for anything

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +          }
I would try to reduce redundancy in this function, e.g. you are checking if its a THERMAL_MGR_EVENT_OS_INTERRUPT twice. Follow this structure: check if the queue receive passes, if it does then read from LM75BD, if reading from LM75BD passes then check if its just a measure cmd and handle that, then check if its a event handle interrupt and handle that

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +          }
Also log that an invalid queue message was received if the events are neither THERMAL_MGR_EVENT_OS_INTERRUPT or THERMAL_MGR_EVENT_MEASURE_TEMP_CMD

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +          addTemperatureTelemetry(temp);
You don't need to call this if its an OS Interrupt, just call overTemperatureDectected and safeOperatingConditions

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +    if (eventReceived == pdTRUE) {
nitpick: you can just put xQueReceive inside the if and avoid creating a BaseType_t variable

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +    error_code_t errCode;
You can create the errCode after xQueueReceive passes, since the first use for this is on the readLM75BD driver call

2024-09-15 20:25 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +    BaseType_t eventReceived = xQueueReceive(thermalMgrQueueHandle, &event, 10);
You can drop the waiting time from 10

2024-09-15 21:59 UTC, Yarik-Popov requested changes
Overall quite good, minor changes otherwise

2024-09-15 21:59 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  if (xQueueSend(thermalMgrQueueHandle, event, 0) != pdTRUE) {
Add a check that the queue handle isn't null. If it is return invalid state

2024-09-15 21:59 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +      LOG_IF_ERROR_CODE(readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temp));
Add a check after this for the errCode of success. We only want successful temp reads to be used

2024-09-15 21:59 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +        LOG_ERROR_CODE(ERR_CODE_INVALID_STATE);
Probably beat to define a new error code for invalid events such as ERR_CODE_INVALID_EVENT

2024-09-15 21:59 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  RETURN_IF_ERROR_CODE(i2cReceiveFrom(devAddr, dataBytes, 2));
Use sizeof(dataBytes) instead of 2 here

2024-09-15 21:59 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  RETURN_IF_ERROR_CODE(i2cSendTo(devAddr, ptrBytes, 1));
Use sizeof(ptrBytes) instead of 1

2024-09-15 23:43 UTC, Yarik-Popov requested changes
Some minor changes left

2024-09-15 23:43 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +      LOG_IF_ERROR_CODE(readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temp));
You should only be reading the temperature when an event tells you to. So move this into the if and elif blocks

2024-09-15 23:43 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +      if (event.type == THERMAL_MGR_EVENT_MEASURE_TEMP_CMD && errCode) {
Instead, it is better to add an if(errCode != success) continue; statement instead after each read

2024-09-15 23:43 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  if (xQueueSend(thermalMgrQueueHandle, event, 0) != pdTRUE) {
It is more readable to use == NULL instead

2024-09-16 15:35 UTC, Yarik-Popov commented
Great job. You finished the onboarding. Dm me your email and I'll add you to the notion

2024-09-16 15:36 UTC, closed without merging