Successfully completed the Onboarding Challenge
UWOrbital/OBC-Firmware-Onboarding pull request #160
Opened 2024-09-25 20:32 UTC by not-finley

Passed Tests:
<img width="725" alt="TestsSuite" src="https://github.com/user-attachments/assets/3335d957-103d-4c1d-a146-3e8947502872">

Integration Test:
<img width="1024" alt="Integration Test" src="https://github.com/user-attachments/assets/50ff3f92-b175-4ba3-ad65-04a0f4541521">

2024-09-25 22:39 UTC, Yarik-Popov requested changes
Overall good first start. Some changes are needed

2024-09-25 22:39 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  i2cReceiveFrom(devAddr, tempData, sizeof(tempData));
These should be wrapped inside of the RETURN_IF_ERROR_CODE macro

2024-09-25 22:39 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  }
This code is redundant, just do multiplication and store it

2024-09-25 22:39 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
>  error_code_t readTempLM75BD(uint8_t devAddr, float *temp) {
Check that the temp is not null before use

2024-09-25 22:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  xQueueSend(thermalMgrQueueHandle, event, portMAX_DELAY);
Lots of things need to be changed here
- always check non-void functions for a return code
- check that the event and thermalMgrQueueHandle aren't null, returning the appropriate error codes
- the delay should be 0 and not portMAX_DELAY as that will block when called in isr if the queue is full which is not what we want

2024-09-25 22:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +        lm75bd_config_t config = *(lm75bd_config_t *) pvParameters;
Pull this to be before the loop

2024-09-25 22:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +        readTempLM75BD(config.devAddr, &temp);
LOG_IF_ERROR_CODE followed by a if(errCode != success) continue; line

2024-09-25 22:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +        readTempLM75BD(config.devAddr, &temp);
Same thing here

2024-09-25 22:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +      if (pvbuffer.type == THERMAL_MGR_EVENT_MEASURE_TEMP_CMD) {
Add an else clause that logs a custom error code for invalid events received

2024-09-25 22:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.h
> +  THERMAL_MGR_EVENT_INTERUPT,
Make this name more descriptive by including OS or OVER_TEMP inside of it

2024-09-25 23:14 UTC, Navtajh04 requested changes

2024-09-25 23:14 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  uint8_t tempData[2];
generally a good idea to initialize all variables. `uint8_t tempData[2] = {0};`

2024-09-25 23:14 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +  thermal_mgr_event_type_t event = THERMAL_MGR_EVENT_INTERUPT;
this is of type `thermal_mgr_event_type_t`, but the receiving queue is expecting type `thermal_mgr_event_t`

2025-09-07 03:52 UTC, Adityya-K commented
Closed due to a lot of time passing.

2025-09-07 03:52 UTC, closed without merging