Submission for Onboarding Challenge
UWOrbital/OBC-Firmware-Onboarding pull request #17
Opened 2022-09-21 18:03 UTC by mangoqwq

2022-09-21 22:57 UTC, dgobalak requested changes
Looks really good overall! Just a few minor comments.

2022-09-21 22:57 UTC, dgobalak commented on onboarding/source/amb_light_service.c
> +static void adcStartConversion_selChn(adcBASE_t *adc, unsigned channel, unsigned fifo_size, unsigned group) {
To improve clarity, change all `unsigned` arguments/variables to the appropriate fixed-size integer type (like `uint8_t` or `uint32_t`)

2022-09-21 22:57 UTC, dgobalak commented on onboarding/source/amb_light_service.c
> +    if (event == MEASURE_LIGHT) {
Although this works for the challenge, it'd make more sense to send any event to the queue, not just MEASURE_LIGHT. I.e. no need for this if statement.

2022-09-21 22:57 UTC, dgobalak commented on onboarding/source/amb_light_service.c
> +        uint32 sensor_data = getLightSensorData();
We typically use the fixed-size integer types with the `_t` suffix, such as `uint32_t`. They're both exactly the same, but it's good to keep things consistent.

2022-09-21 22:57 UTC, dgobalak commented on onboarding/source/amb_light_service.c
> +        uint32 sensor_data = getLightSensorData();
Make this change anywhere you use `uint32`. You'll need to make sure that `stdint.h` is included

2022-09-22 00:54 UTC, mangoqwq commented
I fixed the requested changes!

2022-09-22 01:52 UTC, dgobalak requested changes

2022-09-22 01:52 UTC, dgobalak commented on onboarding/source/amb_light_service.c
> +    BaseType_t returned = xQueueSend(lightServiceQueue, (void *) &event, (TickType_t) 0);
`xQueueSend` expects a pointer to the event and `sendToLightServiceQueue` takes this pointer as an argument. So you should be passing `event` into xQueueSend, not `&event`

2022-09-22 01:52 UTC, dgobalak commented on onboarding/source/controller.c
> +    uint8_t returned = sendToLightServiceQueue(MEASURE_LIGHT);
`sendToLightServiceQueue` expects a pointer to the event. So something like:
```
light_event_t event = MEASURE_LIGHT;
sendToLightServiceQueue(&event);
```

2022-09-22 01:58 UTC, mangoqwq commented
Fixed (hopefully).

2022-09-22 02:11 UTC, dgobalak commented
Great job! If you want, you can test your program on the RM46 LaunchPad at the next work session. If not, feel free to pick up a new task to work on from the task board. I'll add you to the Notion and GitHub.

2022-09-22 02:11 UTC, closed without merging