Completed the onboarding tasks.
UWOrbital/OBC-Firmware-Onboarding pull request #182
Opened 2024-10-14 05:30 UTC by alboainin

# Purpose
Explain the purpose of the PR here, including references to any existing Notion tasks.

# New Changes
- Explain new changes

# Testing
- Explain tests that you ran to verify code functionality.

# Outstanding Changes
- If there are non-critical changes (i.e. additional features) that can be made to this feature in the future, indicate them here.

2024-10-14 05:47 UTC, kepler452b123 requested changes

2024-10-14 05:47 UTC, kepler452b123 commented on lm75bd/lm75bd.c
> -
always check if pointer arguments are null, in which case return error code invalid arg

2024-10-14 05:47 UTC, kepler452b123 commented on lm75bd/lm75bd.c
> +  i2cReceiveFrom(devAddr, buff, 2);
wrap these in RETURNIFERRORCODE (see onboarding challenge doc for more info- we have a section on error/logging macros)

2024-10-14 05:47 UTC, kepler452b123 commented on lm75bd/lm75bd.c
> +  uint8_t buff[2];
its good practice to initialize buffers (just init to 0)

2024-10-14 05:47 UTC, kepler452b123 commented on lm75bd/lm75bd.h
> +#define LM75BD_OBC_I2C_ADDR 0x4F
0x4FU for consistency

2024-10-14 05:47 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
>    /* Send an event to the thermal manager queue */
check if event is null

2024-10-14 05:47 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
>    /* Send an event to the thermal manager queue */
check if queue is null (return error code invalid state if so)

2024-10-14 05:47 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +  portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
you can just use thermalMgrSendEvent

2024-10-14 05:47 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +  float currentTemp;
initialize this float later, after checking the event type

2024-10-14 05:47 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +			addTemperatureTelemetry(currentTemp);
you need to add another event type for OS thermal interrupt events (name it suitably). if its a measure temp cmd, just get the temperature and log it. if its an thermal os interrupt event, get the temperature and call overTempDetected() or safeOperatingCond based on the temp. else log (using LOG_ERROR_CODE) that an invalid event type was received (might need to edit sys/errors.h and add a new error)

2024-10-14 06:59 UTC, alboainin commented
I have uploaded the changes, can you please confirm if it's correct. And if so, what's the next step for the onboarding.

2024-10-14 13:39 UTC, Yarik-Popov requested changes
Overall good, some improvements are needed

2024-10-14 13:39 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  	LOG_ERROR_CODE(ERR_CODE_INVALID_ARG);
No need to log here. It will be logged by the task calling this function

2024-10-14 13:39 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  RETURN_IF_ERROR_CODE(i2cReceiveFrom(devAddr, buff, 2));
Use sizeof the pointer/argument instead of hardcoding 1 and 2

2024-10-14 13:39 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  tempRaw = tempRaw >> 7;
This should be 5 not 7

2024-10-14 13:39 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  *temp = tempRaw * 0.5;
This should be 0.125

2024-10-14 13:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  if (xQueueSend(thermalMgrQueueHandle, event, 0) != pdPASS) {
Check that the queue handle is not null, returning invalid state if it is

2024-10-14 13:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +			} else if (currentTemp < 75.0) {
Use the macros defined in the header instead of hardcoding values here

2024-10-14 13:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +			LOG_IF_ERROR_CODE(readTempLM75BD(config.devAddr, &currentTemp));
You want to add a if(errCode != success) continue; line after this one. Don't worry about setting errCode as it will be set by this macro

2024-10-14 13:39 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  lm75bd_config_t config = *(lm75bd_config_t *) pvParameters;
For space wise its generally better to use a pointer to the pvParametera instead of dereference here.

2024-10-14 22:15 UTC, alboainin commented
Hello, Yarik

I have modified the code. Please review this version

2024-10-15 18:53 UTC, Yarik-Popov reviewed
Lgtm, dm me your email and I'll add u to the notion.

2024-10-15 18:53 UTC, closed without merging