Aidan Mo: Completed Onboarding Challenge
UWOrbital/OBC-Firmware-Onboarding pull request #184
Opened 2024-10-20 22:19 UTC by Aloe-Verified

2024-10-21 15:47 UTC, Yarik-Popov requested changes
Overall good start. Some changes are needed

2024-10-21 15:47 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
>  error_code_t readTempLM75BD(uint8_t devAddr, float *temp) {
Check if temp is not null before use, returning invalid arg

2024-10-21 15:47 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  buffer[0] = 0x00;
```suggestion
uint8_t buffer[1] ={0};
```

2024-10-21 15:47 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +    }
Use the RETURN_IF_ERROR_CODE macro instead

2024-10-21 15:47 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  error_code_t error = i2cSendTo(devAddr, buffer, 1);
Use the sizeof(buffer) instead of 1

2024-10-21 15:47 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  if(xQueueSend(thermalMgrQueueHandle, event, portMAX_DELAY) == pdTRUE){
Check that the event and queue handles aren't null, returning invalid arg and invalid state respectively

2024-10-21 15:47 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  uint8_t temperatureData[2];
Initialize buffer

2024-10-21 15:47 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +    }
Use RETURN_IF_ERROR_CODE macro

2024-10-21 15:47 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  error = i2cReceiveFrom(devAddr, temperatureData, 2);
Use sizeof(temperatureData) instead of 2

2024-10-21 15:47 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +#define THERMAL_MGR_EVENT_OS_INTERRUPT 1
This should be added to the enum in the thermal mgr header file

2024-10-21 15:47 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  float temp;
Move the scope of temp down

2024-10-21 15:47 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +        if(readTempLM75BD(thermalSensorAddr, &temp) == ERR_CODE_SUCCESS){
We want to be logging that a read to the temperature sensor failed in both cases

2024-10-21 15:47 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +          else if (temp < 75.0f){
Use the macros defined in the thermal manager header file instead of hardcoding these values

2024-10-21 19:15 UTC, Yarik-Popov requested changes
One minor change left

2024-10-21 19:15 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  }
This should be at the top. No point of calling driver functions or doing computations if you can't store it in temp which is a simple checl

2024-10-22 00:58 UTC, kepler452b123 requested changes
looks good, just one change

2024-10-22 00:58 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +  if(xQueueSend(thermalMgrQueueHandle, event, portMAX_DELAY) == pdTRUE){
this is too long to wait for queue to become lower- consider shortening it to a more reasonable value

2024-10-22 15:41 UTC, Yarik-Popov reviewed
Lgtm, dm me your email and I'll add you to the notion

2024-10-22 15:41 UTC, closed without merging