Prepare for PR
UWOrbital/OBC-Firmware-Onboarding pull request #195
Opened 2024-11-01 02:30 UTC by Navtajh04

# Purpose
Explain the purpose of the PR here, including references to any existing Notion tasks.

# New Changes
- Explain new changes

# Testing
- Explain tests that you ran to verify code functionality.

# Outstanding Changes
- If there are non-critical changes (i.e. additional features) that can be made to this feature in the future, indicate them here.

2024-11-01 02:35 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  /*
check if temp is NULL and return invalid arg err code if it is

2024-11-03 22:06 UTC, Yarik-Popov requested changes
test

2024-11-03 22:06 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
>  error_code_t readTempLM75BD(uint8_t devAddr, float *temp) {
check that temp isnt null before use

2024-11-03 22:14 UTC, Yarik-Popov requested changes
Overall good start. Some changes are needed to improve the code

2024-11-03 22:14 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  uint8_t buffer[2];
Initialize the buffer

2024-11-03 22:14 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  i2cReceiveFrom(devAddr, buffer, 2U);
- [ ] Wrap both calls inside the RETURN_IF_ERROR_CODE macro
- [ ] Use sizeof(sendBuffer) instead of 1
- [ ] Use sizeof(buffer) instead of 2

2024-11-03 22:14 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  uint16_t temperature = 0;
I would move this down to after the i2c calls as this variable will not be used if the calls fails with the RETURN_IF_ERROR_CODE macro. Also, make this an int16_t

2024-11-03 22:14 UTC, Yarik-Popov commented on lm75bd/lm75bd.c
> +  else *temp = -(((~temperature) & (0xFFFF >> 5)) + 1)*0.125;
If temperature is a int16_t then you don't need to do these lines just `*temp=(float)(temperature * 0.125);` will do

2024-11-03 22:14 UTC, Yarik-Popov commented on lm75bd/lm75bd.h
> +#define LM75BD_OBC_I2C_ADDR 0x4FU /* Define the address here */
We just use the hex value without the U ending of the team

2024-11-03 22:14 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  xQueueSend(thermalMgrQueueHandle, event, 0);
- [ ] In general, you should be checking that pointers aren't null before use. So check that event isn't null
- [ ] Check that thermal mgr queue handle isn't null, returning invalid state
- [ ] You should be checking the return value of non-void functions for error codes

2024-11-03 22:14 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  else safeOperatingConditions();
You shouldn't be reading the temperature inside of the isr as the i2c calls are blocking. Just send an event and have the the thermal mgr task handle the event

2024-11-03 22:14 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +    thermal_mgr_event_t data = *(thermal_mgr_event_t *) pvParameters;
In this case, pvParameters isnt of type thermal_mgr_event_t but of the config which isn't the same. So I would just change the line to initialize an empty event instead

2024-11-03 22:14 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +      addTemperatureTelemetry(temperature);
We shouldn't get to this line if the readTemp fails

2024-11-03 22:14 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +      readTempLM75BD(LM75BD_OBC_I2C_ADDR, &temperature);
Log the error code returned

2024-11-03 22:14 UTC, Yarik-Popov commented on services/thermal_mgr/thermal_mgr.c
> +  if(temperature > 75.0){ // only below T hys is safe
Use the macros defined in the lm75bd.h file instead of hardcoding 75

2025-05-06 15:58 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  uint16_t temperature = 0;
Should be int16_t since the temp sensor will give u a 2s compliment value. 

When you shift an unsigned int by 5 right below it should always fill the remaining spaces to the left with 0s, but if you shift a signed int (int16_t) it will fill it with either 1 or 0 to preserve the sign of the number

2025-05-06 15:58 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  uint16_t temperature = 0;
Should be int16_t since the temp sensor will give u a 2s compliment value. 

When you shift an unsigned int by 5 right below it should always fill the remaining spaces to the left with 0s, but if you shift a signed int (int16_t) it will fill it with either 1 or 0 to preserve the sign of the number

2025-05-06 19:25 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  temperature = ((buffer[0] << 8) | buffer[1]) >> 5;
```suggestion
  temperature = (int16_t) ((buffer[0] << 8) | buffer[1]) >> 5;
```

2025-05-06 19:25 UTC, Navtajh04 commented on lm75bd/lm75bd.c
> +  *temp=(float)(temperature * 0.125);
```suggestion
  *temp=((float)temperature) * 0.125;
```

2025-05-07 01:05 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +  thermal_mgr_event_t event = {0};
since you are sending an empty event this wont do anything

You should create a new event for interrupt and send that event to the thermal mgr.

2025-05-07 01:06 UTC, Navtajh04 commented on services/thermal_mgr/thermal_mgr.c
> +      previous = temperature;
thermal mgr should only do this stuff if an interrupt happened, otherwise just add the temperature telemetry

2025-05-14 23:37 UTC, kepler452b123 requested changes
just one thing

2025-05-14 23:37 UTC, kepler452b123 commented on services/thermal_mgr/thermal_mgr.c
> +  xQueueSend(thermalMgrQueueHandle, event, 0);
check if xQueueSend succeeds (it should return pdtrue). if it doesn't, then you need to return that the queue is full

2025-07-06 12:36 UTC, closed without merging