Aryan - Onboarding Challenge
UWOrbital/OBC-Firmware-Onboarding pull request #50
Opened 2023-06-30 15:01 UTC by AesthicEthics

# Purpose
Onboarding Challenge Review PR

2023-07-01 05:31 UTC, dgobalak requested changes
Looks good. Just a few comments

2023-07-01 05:31 UTC, dgobalak commented on drivers/source/serial_io.c
> +    if (sciLinMutex != NULL){
This check is done on line 64 so u don't need to do it again.

2023-07-01 05:31 UTC, dgobalak commented on drivers/source/serial_io.c
> +        if (xSemaphoreTake( sciLinMutex, ( TickType_t ) UART_MUTEX_BLOCK_TIME == pdTRUE)){
Use `mutex` so we can support printing using either the SCI1 or SCI2/sciLin ports.

2023-07-01 06:00 UTC, Navtajh04 commented on drivers/source/serial_io.c
> +        if (xSemaphoreTake( sciLinMutex, ( TickType_t ) UART_MUTEX_BLOCK_TIME == pdTRUE)){
this should be `if (xSemaphoreTake( sciLinMutex, ( TickType_t ) UART_MUTEX_BLOCK_TIME) == pdTRUE)` ie you're trying to compare the return value of xSemaphoreTake to see if it's successful and not UART_MUTEX_BLOCK_TIME

2023-07-02 07:53 UTC, dgobalak reviewed
lgtm. I'll close this PR now

2023-07-02 07:54 UTC, closed without merging